(function(){
'use strict';
const OWNER=['ionut29019@gmail.com'],ACTIVE=new Set(['attivo','active','approvato','approved']);
let auth=null,db=null,user=null,profile=null,role='';
const $=id=>document.getElementById(id);
function message(v){const e=$('loginMessage');if(e)e.textContent=v||''}
function show(ok,text=''){document.body.classList.toggle('auth-ready',ok);document.body.classList.toggle('auth-locked',!ok);if($('loginScreen'))$('loginScreen').hidden=ok;if($('snowApp'))$('snowApp').hidden=!ok;message(text)}
async function authorize(u){const s=await db.collection('platformUsers').doc(u.uid).get();profile=s.exists?s.data():null;const email=String(u.email||'').toLowerCase();if(OWNER.includes(email)){role='admin';return true}if(!profile||profile.banned===true)return false;const st=String(profile.statoAccount||profile.accountStatus||'').toLowerCase(),legacy=!st&&profile.profileMigratedByEmail!==false;if(!legacy&&!ACTIVE.has(st))return false;const r=String(profile.role||profile.ruolo||'').toLowerCase();role=r==='ufficio'?'ufficio':'operatore';return true}
function boot(){const cfg=window.VARGA_FIREBASE_CONFIG;if(!cfg||typeof firebase==='undefined'){show(false,'Configurazione accesso non disponibile.');return}const app=firebase.apps.find(a=>a.name==='vargaPianoNeve')||firebase.initializeApp(cfg,'vargaPianoNeve');auth=app.auth();db=app.firestore();auth.onAuthStateChanged(async u=>{user=u||null;if(!u){show(false);return}try{if(await authorize(u)){show(true);window.dispatchEvent(new CustomEvent('varga-auth-ready',{detail:{uid:u.uid,email:u.email,role}}))}else{show(false,'Account non autorizzato nel Varga Gestionale.');await auth.signOut()}}catch(e){console.warn(e);show(false,'Impossibile verificare autorizzazione.')}})}
async function emailLogin(){message('Accesso…');try{await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithEmailAndPassword($('loginEmail').value.trim(),$('loginPassword').value)}catch(e){message('Email o password non corrette.')}}
function startAuth(){try{boot();const lb=$('loginButton'),lp=$('loginPassword'),gb=$('loginGoogleButton');if(lb)lb.onclick=emailLogin;if(lp)lp.addEventListener('keydown',e=>{if(e.key==='Enter')emailLogin()});if(gb)gb.onclick=async()=>{try{await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(e){message('Accesso Google non riuscito.')}}}catch(e){console.error('Varga auth boot',e);show(false,'Errore avvio accesso: '+(e.message||e))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startAuth,{once:true});else startAuth();
window.VargaSnowCloud={get user(){return user},get role(){return role},async saveSession(payload){if(!user)return false;await db.collection('pianoNeveUsers').doc(user.uid).collection('sessions').doc('active').set(Object.assign({},payload,{uid:user.uid,userEmail:user.email||'',updatedAt:firebase.firestore.FieldValue.serverTimestamp()}),{merge:true});return true},async loadSession(){if(!user)return null;const s=await db.collection('pianoNeveUsers').doc(user.uid).collection('sessions').doc('active').get();return s.exists?s.data():null},async clearSession(){if(user)await db.collection('pianoNeveUsers').doc(user.uid).collection('sessions').doc('active').delete()},signOut(){return auth&&auth.signOut()}};
})();