(function(){
'use strict';
const style=document.createElement('style');style.textContent=`
#territoryPanel[hidden]{display:none!important}#territoryPanel{position:fixed;inset:0;z-index:20000;background:#06111bea;display:grid;place-items:center;padding:14px;font-family:system-ui,sans-serif;color:#eaf6ff}
#territoryPanel *{box-sizing:border-box}#territoryPanel .tc{width:min(680px,100%);max-height:94dvh;overflow:auto;background:linear-gradient(155deg,#173448,#0b1926 70%);border:1px solid #416075;border-radius:24px;padding:22px;box-shadow:0 22px 80px #0008}
#territoryPanel .top{display:flex;justify-content:space-between;gap:12px;align-items:start}#territoryPanel h2{margin:4px 0 5px;font-size:24px}#territoryPanel p{color:#bad1dc;margin:5px 0 18px}#territoryPanel .badge{font-size:12px;color:#9be3dc;font-weight:700;letter-spacing:.08em}
#territoryPanel button{cursor:pointer;border:0;border-radius:12px;padding:12px 14px;font-weight:700}#territoryPanel .close{background:#2b4354;color:white}#territoryPanel input[type=search]{width:100%;background:#0b1c2b;color:white;border:1px solid #587186;border-radius:12px;padding:14px;font-size:16px}
#territoryPanel .step{background:#10283a;border:1px solid #29475a;border-radius:16px;padding:15px;margin:12px 0}#territoryPanel .step b{display:block;margin-bottom:8px}#territoryPanel .chips{display:flex;gap:8px;flex-wrap:wrap;max-height:160px;overflow:auto}#territoryPanel .chip{background:#28445a;color:#fff;border:1px solid #456477}#territoryPanel .chip[aria-pressed=true]{background:#baf5e7;color:#0c2632}#territoryPanel .empty{color:#aac1cc;font-size:14px;padding:10px 0}
#territoryPanel .footer{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between}#territoryPanel .primary{background:#9be8d7;color:#0a2530}#territoryPanel .summary{font-size:14px;color:#d4e9ee}#territoryPanel .note{font-size:13px;color:#9db4c2;margin-top:14px}
`;document.head.appendChild(style);
const anchor=document.getElementById('adminManageRoutes');if(!anchor)return;
const trigger=document.createElement('button');trigger.id='territoryOpen';trigger.className='adminArchiveBtn';trigger.textContent='🗺️ PREPARA ZONE COMMESSA';trigger.hidden=true;anchor.insertAdjacentElement('afterend',trigger);
const sync=()=>{trigger.hidden=anchor.hidden||getComputedStyle(anchor).display==='none'};new MutationObserver(sync).observe(anchor,{attributes:true,attributeFilter:['hidden','style','class']});sync();
const panel=document.createElement('div');panel.id='territoryPanel';panel.hidden=true;panel.innerHTML=`<div class="tc" role="dialog" aria-modal="true" aria-labelledby="territoryTitle"><div class="top"><div><span class="badge">PREPARAZIONE · NESSUNA COMMESSA CREATA</span><h2 id="territoryTitle">Dove si lavora?</h2><p>Scegli uno o più comuni e quartieri. Puoi cambiarli quando vuoi.</p></div><button class="close" id="territoryClose" aria-label="Chiudi">✕</button></div><label for="territorySearch">🔎 Cerca comune o quartiere</label><input id="territorySearch" type="search" placeholder="Es. Bologna, Navile…"><div class="step"><b>1 · Comuni <span id="municipalityCount"></span></b><div class="chips" id="municipalityChips"></div></div><div class="step"><b>2 · Quartieri <span id="neighborhoodCount"></span></b><div class="chips" id="neighborhoodChips"></div><div class="note">Puoi scegliere più quartieri; le strade che attraversano confini verranno controllate in tutte le zone.</div></div><div class="step"><b>3 · Riepilogo</b><div class="summary" id="territorySummary" aria-live="polite"></div></div><div class="footer"><button class="close" id="territoryClear">Azzera scelta</button><button class="primary" id="territorySave">💾 SALVA SELEZIONE</button></div><div class="note" id="territoryMessage">I confini ufficiali saranno collegati successivamente. Nessun PDF importato.</div></div>`;document.body.appendChild(panel);
const $=id=>document.getElementById(id);let previousFocus=null;
let saved;try{saved=JSON.parse(localStorage.getItem('snowTerritoryDraft')||'{}')}catch{saved={}}
const selected={municipalities:new Set(saved.municipalities||[]),neighborhoods:new Set(saved.neighborhoods||[])};
function zones(){const local=window.VARGA_TERRITORY_BOUNDARIES?.features||[];const osm=window.VargaOSMBoundaries?.cachedFeatures()?.features||[];return window.VargaTerritory?window.VargaTerritory.createResolver({type:'FeatureCollection',features:[...local,...osm]}).list().filter(z=>z.municipality):[]}
async function loadBoundaries(){if(window.VARGA_TERRITORY_BOUNDARIES)return;try{const response=await fetch('commesse/confini.geojson',{cache:'no-cache'});if(!response.ok)throw Error('Dati non pubblicati');const data=await response.json();if(data.type!=='FeatureCollection'||!Array.isArray(data.features))throw Error('GeoJSON non valido');window.VARGA_TERRITORY_BOUNDARIES=data;$('territoryMessage').textContent='Confini territoriali caricati: '+data.features.length+' zone disponibili.';}catch(e){$('territoryMessage').textContent='Confini non ancora pubblicati: '+e.message+'. Nessuna zona inventata.';}render();}
function render(){const all=zones(),q=$('territorySearch').value.toLocaleLowerCase('it');const municipalities=[...new Set(all.map(z=>z.municipality))].sort((a,b)=>a.localeCompare(b,'it'));const neighborhoods=[...new Set(all.filter(z=>!selected.municipalities.size||selected.municipalities.has(z.municipality)).map(z=>z.neighborhood).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'it'));
function chips(id,values,set){const box=$(id);box.replaceChildren();for(const value of values.filter(v=>v.toLocaleLowerCase('it').includes(q))){const b=document.createElement('button');b.className='chip';b.textContent=value;b.setAttribute('aria-pressed',String(set.has(value)));b.onclick=()=>{set.has(value)?set.delete(value):set.add(value);render()};box.appendChild(b)}if(!box.children.length){const e=document.createElement('span');e.className='empty';e.textContent=all.length?'Nessuna corrispondenza':'Confini non ancora disponibili: la selezione sarà attiva quando verranno caricati.';box.appendChild(e)}}
chips('municipalityChips',municipalities,selected.municipalities);chips('neighborhoodChips',neighborhoods,selected.neighborhoods);$('municipalityCount').textContent='('+selected.municipalities.size+')';$('neighborhoodCount').textContent='('+selected.neighborhoods.size+')';$('territorySummary').textContent=(selected.municipalities.size?[...selected.municipalities].join(', '):'Nessun comune selezionato')+' · '+(selected.neighborhoods.size?[...selected.neighborhoods].join(', '):'Tutti i quartieri dei comuni scelti');$('territorySave').disabled=!selected.municipalities.size}
function close(){panel.hidden=true;previousFocus?.focus()}trigger.onclick=()=>{previousFocus=document.activeElement;panel.hidden=false;render();loadBoundaries();$('territorySearch').focus()};$('territoryClose').onclick=close;$('territorySearch').oninput=render;$('territoryClear').onclick=()=>{selected.municipalities.clear();selected.neighborhoods.clear();render()};$('territorySave').onclick=()=>{localStorage.setItem('snowTerritoryDraft',JSON.stringify({municipalities:[...selected.municipalities],neighborhoods:[...selected.neighborhoods]}));$('territoryMessage').textContent='✓ Selezione salvata su questo dispositivo. Non è stata creata alcuna commessa.'};panel.addEventListener('keydown',e=>{if(e.key==='Escape')close()});panel.addEventListener('click',e=>{if(e.target===panel)close()});const osmRow=document.createElement('div');osmRow.className='step';osmRow.innerHTML='<b>🌍 Aggiungi comune da OpenStreetMap</b><input id="osmMunicipality" type="search" placeholder="Es. Castel Maggiore"><button class="primary" id="osmMunicipalityLoad" type="button">CERCA CONFINE</button><div class="note" id="osmMunicipalityStatus" aria-live="polite">I confini scaricati restano disponibili offline su questo dispositivo.</div>';panel.querySelector('.footer').before(osmRow);$('osmMunicipalityLoad').onclick=async()=>{const name=$('osmMunicipality').value.trim();if(!name)return;$('osmMunicipalityLoad').disabled=true;$('osmMunicipalityStatus').textContent='Cerco il confine amministrativo OSM…';try{const f=await window.VargaOSMBoundaries.loadMunicipality(name);selected.municipalities.add(f.properties.municipality);$('osmMunicipalityStatus').textContent='✓ Confine di '+name+' salvato per l’uso offline.';render()}catch(e){$('osmMunicipalityStatus').textContent='⚠ '+e.message}finally{$('osmMunicipalityLoad').disabled=false}};render();
})();